### ISSUE TITLE
refactor index.html to have separate js and css files

### ISSUE THREAD

**Issue by tbags** [tbags/django-image-annotation-tool#6]
https://github.com/tbags/django-image-annotation-tool/blob/master/image_metadata/templates/index.html

**Comment by prateethvnayak** [comment]
@tbags I did the css refactoring. Was trying to link the css to html file. The relative path seems to be a mistake. I am unable to get the relative path to the css file from the server root. Whats the server root dir ? [Line 36](https://github.com/tbags/django-image-annotation-tool/blob/8d41ca607052fe262b4af711e34fdc9f6516724b/image_metadata/templates/index.html#L36)

**Comment by prateethvnayak** [comment]
@SanjayYr Mestre. Refactoring branch use madi for Js refactor. Nanu CSS madideeni. href swalpa miss hodta idey.

**Comment by tbags** [comment]
try running: `python manage.py collectstatic`

**Comment by tbags** [comment]
add this to [link](https://github.com/tbags/django-image-annotation-tool/blob/Refactoring/viapp/settings.py): ```STATIC_ROOT = os.path.join(BASE_DIR, 'static')```

**Comment by tbags** [comment]
inside your index.html, you need to import the css like so:  ```html
<link href="{% static "//canvas.css" %}" rel="stylesheet">
```

**Comment by tbags** [comment]
inside index.html import css like so: `<link href="{% static "//canvas.css" %}" rel="stylesheet">`

**Comment by prateethvnayak** [comment]
Closing for now. Revisit if it breaks.
